version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 HENRO.wsgi:application
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: HENRO.settings
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

