services:
  web:
    image: henro:web
    container_name: henro-web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - type: volume
        source: socket
        target: /var/run/gunicorn
    ports:
      - 8000:80
    depends_on:
      - app

  app:
    image: henro:app
    container_name: henro-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - type: volume
        source: socket
        target: /var/run/gunicorn
    env_file:
      - docker/app/.env
    command: gunicorn HENRO.wsgi:application --bind unix:/var/run/gunicorn.sock

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: henro-db
    volumes:
      - type: volume
        source: volume-db
        target: /var/lib/postgresql/data
    env_file:
      - docker/db/.env
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-postgres}
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 3s

volumes:
  volume-db:
    name: volume-db-volume
    driver: local
  socket:
    name: django-socket
    driver: local