# Generated by Django 5.1 on 2024-08-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nikki', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
