<<<<<<< HEAD
# Generated by Django 5.0.8 on 2024-08-22 12:03
=======
# Generated by Django 5.1 on 2024-08-22 11:55
>>>>>>> ee98d7f513ac2442fefed26b1e5ed56a65e69e8f

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
