# Generated by Django 5.0.8 on 2024-08-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goshuin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temple',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='temple',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
